AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWSLambdaJava21WithAuroraDSQLAndPgJDBC 
  Sample SAM Template

Parameters:
  Stage:
    Type: String
    Default: orders
    
  AuroraDSQLClusterId:
    Description: "Aurora DSQL Cluster ID"
    Type: String
    
Globals:
  Function:
    CodeUri: target/aws-lambda-java-21-with-aurora-dsql-and-pgjdbc-1.0.0-SNAPSHOT.jar
    Runtime: java21
    #SnapStart:
     #ApplyOn: PublishedVersions     
    Timeout: 30 
    MemorySize: 1024
    Architectures:
      #- arm64
      - x86_64  
    #Tracing: Active
    Environment:
      Variables:
        JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
        AURORA_DSQL_CLUSTER_ENDPOINT: !Sub ${AuroraDSQLClusterId}.dsql.${AWS::Region}.on.aws
        REGION: !Sub ${AWS::Region}

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      #TracingEnabled: true
      Name: AWSLambdaJava21WithDSQLAndPgJDBCAPI
      Description: Api for AWSLambdaJava21WithDSQLAndPgJDBC
      #AccessLogSetting:
        #DestinationArn: !Sub ${MyApiLogGroup.Arn} # This Log Group is already created within our SAM Template
        #Format: "{'integrationLatency':'$context.integrationLatency', 'latency':'$context.responseLatency', 'requestId':'$context.requestId', 'ip': '$context.identity.sourceIp', 'caller':'$context.identity.caller', 'user':'$context.identity.user','requestTime':'$context.requestTime', 'xrayTraceId':'$context.xrayTraceId', 'wafResponseCode':'$context.wafResponseCode', 'httpMethod':'$context.httpMethod','resourcePath':'$context.resourcePath', 'status':'$context.status','protocol':'$context.protocol', 'responseLength':'$context.responseLength' }"
      #MethodSettings:
       # - MetricsEnabled: True
       #   ResourcePath: '/*'
       #   HttpMethod: '*'
      Auth:
        ApiKeyRequired: true  # sets for all methods
  
        
  MyApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
       LogGroupName: !Sub "/aws/apigateway/${MyApi}"
       RetentionInDays: 7
      
  MyApiUsagePlan:
     Type: AWS::ApiGateway::UsagePlan
     DependsOn:  
        - MyApiStage
     Properties:
      ApiStages: 
        - ApiId: !Ref MyApi
          Stage: !Ref Stage
      UsagePlanName: AWSLambdaJava21WithDSQLAndPgJDBCAPIUsagePlan
      Description: Usage plan for AWSLambdaJava21WithDSQLAndPgJDBCAPI
      Quota:
          Limit: 500000
          Period: DAY
      Throttle:
          RateLimit:  10000
          BurstLimit: 5000   

  MyApiKey: 
    Type: AWS::ApiGateway::ApiKey
    DependsOn:  
       - MyApiStage
    Properties: 
      Name: "AWSLambdaJava21WithDSQLAndPgJDBCApiKey"
      Description: "AWSLambdaJava21WithDSQLAndPgJDBC API Key"
      Enabled: true
      GenerateDistinctId: false
      Value: a6ZbcDefQW12BN56WEDS7
      StageKeys:
        - RestApiId: !Ref MyApi
          StageName: !Ref Stage

  MyApiUsagePlanKey:
      Type: "AWS::ApiGateway::UsagePlanKey"
      DependsOn: 
      - MyApi
      Properties:
        KeyId: !Ref MyApiKey
        KeyType: API_KEY
        UsagePlanId: !Ref MyApiUsagePlan


  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateOrderWithJava21Lambda
      AutoPublishAlias: liveVersion
      Handler: software.amazonaws.example.order.handler.CreateOrderHandler::handleRequest
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dsql:DbConnectAdmin
              Resource: !Sub arn:aws:dsql:${AWS::Region}:${AWS::AccountId}:cluster/${AuroraDSQLClusterId}
              
      Events:
        GetRequestById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /orders
            Method: post    

  CreateOrderFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CreateOrderFunction}"
      RetentionInDays: 7


  GetOrderByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetOrderByIdWithJava21Lambda
      AutoPublishAlias: liveVersion
      Handler: software.amazonaws.example.order.handler.GetOrderByIdHandler::handleRequest
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dsql:DbConnectAdmin
              Resource: !Sub arn:aws:dsql:${AWS::Region}:${AWS::AccountId}:cluster/${AuroraDSQLClusterId}
              
      Events:
        GetRequestById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /orders/{id}
            Method: get     
            
            
  GetOrderByIdFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetOrderByIdFunction}"
      RetentionInDays: 7


  UpdateOrderStatusByOrderIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UpdateOrderStatusByOrderIdWithJava21Lambda
      AutoPublishAlias: liveVersion
      Handler: software.amazonaws.example.order.handler.UpdateOrderStatusByOrderIdHandler::handleRequest
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dsql:DbConnectAdmin
              Resource: !Sub arn:aws:dsql:${AWS::Region}:${AWS::AccountId}:cluster/${AuroraDSQLClusterId}
              
      Events:
        GetRequestById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /orders/updatestatus/{id}
            Method: put    

  UpdateOrderStatusByOrderIdFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${UpdateOrderStatusByOrderIdFunction}"
      RetentionInDays: 7


Outputs:
  AWSLambdaJava21WithDSQLAndPgJDBCAPIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for AWS Lambda Java 21 With Aurora DSQL And PgJDBC"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/orders"
